### ISSUE TITLE
How do I get the patched version of the MLC dataset?

### ISSUE THREAD

**Issue by hongyonghan** [JordanMakesMaps/MDNet#2]
How do I get the patched version of the MLC dataset? The MLC datasets of the readme is raw data rather than processed data.

**Comment by JordanMakesMaps** [comment]
Hi @hongyonghan, from that link you'll download the data (jpg images, text annotations) using the links:

`package of images for coral recognition [YEAR]`

You'll then submit to the manager some info and be provided a download link. The text annotations provided will tell you the image, column, row and label of each annotation. To create patches from those images, I suggest using a function that crops a sub-image (i.e., patch) from the image centered on the respective annotation (i.e., XY pixel). A non-tested example for how to do this is below:

```python
import numpy as np
import pandas as pd
from skimage.io import imsave, imread

image_path = "image.jpg"
label_path = "label.csv"

image = imread(image_path)
label = pd.read_csv(label_path, index_col=0)


patch_size = 224

for i, r in label.iterrows():
    x, y = r['column'], ['row']
    l = r['label']
    patch = image[patch_size//2 - y : patch_size//2 + y, patch_size//2 - x : patch_size//2 + x]
    imsave(arr=patch, fname="./" + l  + "/" + os.path.basename(label_path) + "_" + str(y) + "_" + str(x) + ".jpg)

```

**Comment by hongyonghan** [comment]
Thank for your help!

**Comment by JordanMakesMaps** [comment]
No problem, let me know if you run into any other issues.
